"""Add image_url field to User model

Revision ID: 609da396c459
Revises: 7d63d0ec728f
Create Date: 2023-10-13 14:26:06.839261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609da396c459'
down_revision = '7d63d0ec728f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('profile_picture_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
