"""Update new daily ass

Revision ID: ca617ba904d2
Revises: c9e313e3e2e3
Create Date: 2023-10-21 10:26:32.258680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca617ba904d2'
down_revision = 'c9e313e3e2e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_assessment', schema=None) as batch_op:
        batch_op.alter_column('stress_level',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('positive_affect_rating',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_assessment', schema=None) as batch_op:
        batch_op.alter_column('positive_affect_rating',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=2),
               existing_nullable=True)
        batch_op.alter_column('stress_level',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=2),
               existing_nullable=True)

    # ### end Alembic commands ###
